[features]
seeds = true
skip-lint = false
[programs.localnet]
crud_indexing = "3YtbN69K6qkLsc3nWCPrzSkyNmwzF5uRppmfm9FyYz4k"
nft_style_two = "3YtbN69K6qkLsc3nWCPrzSkyNmwzF5uRppmfm9FyYz4k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noahgundotra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
